# Generated by Django 5.2 on 2025-04-04 10:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(default='Adresse inconnue', max_length=100)),
                ('referentiel', models.CharField(choices=[('DEV_WEB', 'Développeur Web'), ('REFERENT_DIGITAL', 'Référent Digital'), ('DIGITAL_CREATOR', 'Digital Creator')], default='DEV_WEB', max_length=100)),
                ('numero_telephone', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir exactement 9 chiffres.', regex='^\\d{9}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apprenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
