# Generated by Django 5.2 on 2025-04-04 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_apprenantprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordinateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(default='Inconnu', max_length=100)),
                ('modele', models.CharField(default='Inconnu', max_length=100)),
                ('processeur', models.CharField(default='Inconnu', max_length=100)),
                ('ram', models.CharField(default='8GB', max_length=100)),
                ('stockage', models.CharField(default='256GB', max_length=100)),
                ('adresse_mac', models.CharField(default='00:00:00:00:00:00', max_length=100, unique=True)),
                ('etat', models.CharField(choices=[('bon', 'Bon état'), ('mineur', 'Problème mineur'), ('majeur', 'Problème majeur')], default='bon', max_length=10)),
                ('apprenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordinateurs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_probleme', models.CharField(choices=[('materiel', 'Problème matériel'), ('logiciel', 'Problème logiciel'), ('ecran', "Problème d'écran"), ('clavier', 'Problème de clavier'), ('batterie', 'Problème de batterie'), ('autre', 'Autre problème')], default='materiel', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('apprenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('ordinateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.ordinateur')),
            ],
        ),
    ]
