# Generated by Django 5.2 on 2025-04-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ordinateur_reportissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprenantprofile',
            name='email',
            field=models.EmailField(default='utilisateur_inconnu@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='apprenantprofile',
            name='nom',
            field=models.CharField(default='Inconnu', max_length=100),
        ),
        migrations.AddField(
            model_name='apprenantprofile',
            name='prenom',
            field=models.CharField(default='Inconnu', max_length=100),
        ),
        migrations.AddField(
            model_name='apprenantprofile',
            name='sexe',
            field=models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], default='H', max_length=10),
        ),
        migrations.AddField(
            model_name='ordinateur',
            name='generation_cpu',
            field=models.CharField(default='Inconnu', max_length=100),
        ),
        migrations.AddField(
            model_name='ordinateur',
            name='generation_serie',
            field=models.CharField(default='Inconnu', max_length=100),
        ),
        migrations.AddField(
            model_name='ordinateur',
            name='numero_serie',
            field=models.CharField(default='Inconnu', max_length=100),
        ),
        migrations.AddField(
            model_name='ordinateur',
            name='serie',
            field=models.CharField(default='Inconnu', max_length=100),
        ),
        migrations.AlterField(
            model_name='apprenantprofile',
            name='referentiel',
            field=models.CharField(choices=[('DEV_WEB', 'Développeur Web'), ('REFERENT_DIGITAL', 'Référent Digital'), ('DIGITAL_CREATOR', 'Digital Creator')], default='Développeur Web', max_length=100),
        ),
    ]
